name: Corex
version: '${version}'
main: dev.corexmc.corex.Corex
description: Modern, Paper-exclusive scripting engine.
authors:
  - tizis0
  - Nybik_YT
  - isnsest
  - Corex Inc
api-version: '1.21'
folia-supported: true
