package dev.corexinc.corex.environment.utils.entities;

import dev.corexinc.corex.environment.tags.core.MapTag;
import net.kyori.adventure.text.Component;
import org.bukkit.Color;
import org.bukkit.DyeColor;
import org.bukkit.Rotation;
import org.bukkit.entity.*;
import org.bukkit.block.data.BlockData;
import org.bukkit.inventory.ItemStack;
import org.bukkit.util.Vector;
import org.joml.Quaternionf;
import org.joml.Vector3f;

public interface LiveEntityView {
    void setCustomName(Component name);
    void setCustomNameVisible(boolean visible);
    void setGlowing(boolean value);
    void setGravity(boolean value);
    void setInvulnerable(boolean value);
    void setSilent(boolean value);
    void setPersistent(boolean persistent);
    void setNbt(MapTag nbt);
    void setFireTicks(int ticks);
    void setFreezeTicks(int ticks);
    void setRemainingAir(int ticks);
    void setFallDistance(float distance);
    void setVelocity(Vector velocity);
    void setRotation(float yaw, float pitch);
    void setMaxHealth(double health);
    void setHealth(double health);
    void setAI(boolean value);
    void setInterpolationDuration(int duration);
    void setInterpolationDelay(int delay);
    void setTranslation(Vector3f translation);
    void setScale(Vector3f scale);
    void setLeftRotation(Quaternionf rotation);
    void setRightRotation(Quaternionf rotation);
    void setViewRange(float range);
    void setBrightness(int block, int sky);
    void setBillboard(Display.Billboard billboard);
    void setTextShadowed(boolean shadowed);
    void setBackgroundColor(Color color);
    void setText(Component text);
    void setItem(ItemStack item);
    void setInteractionWidth(float width);
    void setInteractionHeight(float height);

    void setInvisible(boolean invisible);
    void setVisualFire(boolean visualFire);
    void setTicksLived(int ticks);
    void setPortalCooldown(int ticks);
    void setVisibleByDefault(boolean visible);

    void setGliding(boolean gliding);
    void setSwimming(boolean swimming);
    void setCollidable(boolean collidable);
    void setArrowsInBody(int count);
    void setBeeStingersInBody(int count);
    void setAbsorptionAmount(double amount);
    void setNoDamageTicks(int ticks);
    void setMaxNoDamageTicks(int ticks);
    void setCanPickupItems(boolean value);
    void setRemoveWhenFarAway(boolean value);

    void setShadowRadius(float radius);
    void setShadowStrength(float strength);
    void setDisplayWidth(float width);
    void setDisplayHeight(float height);
    void setGlowColorOverride(Color color);
    void setTeleportDuration(int ticks);

    void setLineWidth(int width);
    void setTextOpacity(byte opacity);
    void setSeeThrough(boolean seeThrough);
    void setDefaultBackground(boolean value);
    void setTextAlignment(TextDisplay.TextAlignment alignment);

    void setItemDisplayTransform(ItemDisplay.ItemDisplayTransform transform);
    void setBlock(BlockData blockData);
    void setInteractionResponsive(boolean responsive);

    EntityType bukkitType();

    void setSheepColor(DyeColor value);
    void setShulkerColor(DyeColor value);
    void setFishBodyColor(DyeColor value);
    void setFishPatternColor(DyeColor value);
    void setFishPattern(TropicalFish.Pattern value);
    void setHorseColor(Horse.Color value);
    void setHorseStyle(Horse.Style value);
    void setLlamaColor(Llama.Color value);
    void setLlamaStrength(int value);
    void setCollarColor(DyeColor value);
    void setCatCollarColor(DyeColor value);
    void setSheared(boolean value);
    void setCowVariant(Cow.Variant value);
    void setPigVariant(Pig.Variant value);
    void setChickenVariant(Chicken.Variant value);
    void setWolfVariant(Wolf.Variant value);
    void setFrogVariant(Frog.Variant value);
    void setCatVariant(Cat.Type value);
    void setSalmonVariant(Salmon.Variant value);
    void setAxolotlVariant(Axolotl.Variant value);
    void setParrotVariant(Parrot.Variant value);
    void setMooshroomVariant(MushroomCow.Variant value);
    void setRabbitType(Rabbit.Type value);
    void setFoxType(Fox.Type value);
    void setSlimeSize(int value);
    void setPhantomSize(int value);
    void setPuffState(int value);
    void setPowered(boolean value);
    void setExplosionRadius(int value);
    void setMaxFuseTicks(int value);
    void setPeek(float value);
    void setAngry(boolean value);
    void setJumpStrength(double value);
    void setTemper(int value);
    void setMaxTemper(int value);
    void setMainGene(Panda.Gene value);
    void setHiddenGene(Panda.Gene value);
    void setCrouching(boolean value);
    void setScreaming(boolean value);
    void setLeftHorn(boolean value);
    void setRightHorn(boolean value);
    void setBeeAnger(int value);
    void setHasNectar(boolean value);
    void setHasStung(boolean value);
    void setCarriedBlock(BlockData value);
    void setPlayerCreated(boolean value);
    void setDerp(boolean value);
    void setZombificationImmune(boolean value);
    void setTrusting(boolean value);
    void setCharging(boolean value);
    void setCanDuplicate(boolean value);
    void setDragonPhase(EnderDragon.Phase value);
    void setProfession(Villager.Profession value);
    void setVillagerType(Villager.Type value);
    void setVillagerLevel(int value);
    void setAge(int value);
    void setBaby(boolean value);
    void setAgeLock(boolean value);
    void setTamed(boolean value);
    void setSitting(boolean value);
    void setSaddled(boolean value);
    void setArms(boolean value);
    void setBasePlate(boolean value);
    void setMarker(boolean value);
    void setSmall(boolean value);
    void setFrameItem(ItemStack value);
    void setFrameRotation(Rotation value);
    void setFrameFixed(boolean value);
    void setFuseTicks(int value);
    void setFallingBlockData(BlockData value);
    void setDropsItem(boolean value);
    void setHurtsEntities(boolean value);
    void setArrowDamage(double value);
    void setPierceLevel(int value);
    void setKnockback(int value);
    void setCritical(boolean value);
    void setPickupStatus(AbstractArrow.PickupStatus value);
    void setCloudRadius(float value);
    void setCloudDuration(int value);
    void setDroppedItem(ItemStack value);
    void setPickupDelay(int value);
    void setExperience(int value);
}
