name: Corex
version: '${version}'
main: dev.corexinc.corex.Corex
description: Modern, Paper-exclusive compiled scripting engine
authors:
  - tizis0
  - Nybik_YT
api-version: '1.21'
folia-supported: true
load: STARTUP
loader: dev.corexinc.corex.CorexLoader